version: "3"

services:
  db:
    container_name: postgres-db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackathon_bi_db_test
    ports:
      - "5432:5432"